### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by nick99nack** [Chaosminecraft/Custom-Encoder#1]
For the love of god please use them. It would look so much better.

[https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)

**Comment by Chaosminecraft** [comment]
Yeah, i agree, I just got in to releasing on Github... And I'm going to look after that after school.

**Comment by Chaosminecraft** [comment]
But the thing is that i use the Github application to push new versions to the repository.

**Comment by Chaosminecraft** [comment]
Because i'm new to GitHub, i'm sorry that this isn't done in an Neat way. I'm planning to make that Happen nick99nack.
